# Generated by Django 2.2 on 2020-11-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
