# Generated by Django 2.2 on 2020-11-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0002_auto_20201107_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.UUIDField(editable=False),
        ),
    ]
